[Variables]

vSkinWidth=450
vSkinHeight=370
vSkinScale=1.5

paddingLeft=15
paddingTop=15
paddingRight=15
paddingBottom=15

vScrollBarHidden=0

;vPath="#CURRENTPATH#Shortcuts"

vHideToolTip=1

vRows=8

vScrollIndex=0

ContainerH=(22*#vSkinScale#)

vPath="C:\Users\*\Gaming\RomGames\Nintendo NES\roms"
vPathEmulator="C:\Users\*\Gaming\RomGames\Nintendo NES\VirtuaNES.exe"
vRomName=
vRomExtension=

Icon1=
Name1=Name01
WholePath1=[""]
Icon2=
Name2=Name02
WholePath2=[""]
Image=

icon3="#vPath#\[mName1].[mExtension1]"
