[Variables]

vSkinWidth=450
vSkinHeight=370
vSkinScale=1.5

paddingLeft=15
paddingTop=15
paddingRight=15
paddingBottom=15

vScrollBarHidden=0

;vPath="#CURRENTPATH#Shortcuts"

vHideToolTip=1

vRows=8

vScrollIndex=0

ContainerH=(22*#vSkinScale#)

vPath="%userprofile%\OneDrive\Gaming\RomGames\Nintendo NES\roms"
vPathEmulator="%userprofile%\OneDrive\Gaming\RomGames\Nintendo NES\VirtuaNES.exe"
vRomName=
vRomExtension=

