
[Variables]

;-------- Enter the number of stocks you want to track below -------------
NumberOfStocks=8

; #### Symbols -----------------------------------
; Find Symbols by going to http://www.cnbc.com then entering the stock/index name you want in the search box. When the page opens look in the top-left address window and make a note of EXACTLY what comes after https://www.cnbc.com/quotes/  If there is a Period "." after the backslash "/" you must include it. or it will not work. 

;eg https://www.cnbc.com/quotes/TSLA  --> Symbol1=TSLA -----------------

;	Units = Number of Units held
;	BuyPrice = Per Unit Price of stock when bought

Symbol1=AAPL
Units1=1
BuyPrice1=146.95

;----------------------------------
Symbol2=FB
Units2=1
BuyPrice2=358.92

;----------------------------------
Symbol3=MSFT
Units3=1
BuyPrice3=286.51

;----------------------------------
Symbol4=AMD
Units4=1
BuyPrice4=118.77

;----------------------------------
Symbol5=INTC
Units5=1
BuyPrice5=53.90

;-----------------------------------
Symbol6=SONY
Units6=1
BuyPrice6=102.26

;-----------------------------------
Symbol7=TMUS
Units7=1
BuyPrice7=142.22

;------------------------------------
Symbol8=NFLX
Units8=1
BuyPrice8=517.35




